name: publish-asf-site

on:
  push:
    branches: [ new-official-website ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: rocketmq-site

      - run: |
          cd $GITHUB_WORKSPACE/rocketmq-site/
          npm run build
          mv build content
          rm .git/ -rf

      - uses: actions/checkout@v2
        with:
          ref: new-website-pre
          path: new-website-pre

      - run: |
          cd $GITHUB_WORKSPACE/new-website-pre/
          git rm -rf .
          cp -Rf $GITHUB_WORKSPACE/rocketmq-site/. .
          ls
          git config --global user.email "action@github.com"
          git config --global user.name "github-action"
          sed -i "/content/d" .gitignore
          git add .
          git status
          git commit -m "[Pre-Release]Latest site on successful build auto-pushed to new-website-pre"
          git push
